ALTER TABLE port ADD COLUMN type VARCHAR(255) DEFAULT 'PLANETARY';
ALTER TABLE port ADD COLUMN latitude REAL;
ALTER TABLE port ADD COLUMN longitude REAL;
ALTER TABLE port ADD COLUMN semi_major_axis REAL;
ALTER TABLE port ADD COLUMN semi_minor_axis REAL;
ALTER TABLE port ADD COLUMN inclination REAL;