CREATE TABLE planet (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    radius_km REAL NOT NULL
);

ALTER TABLE port ADD COLUMN planet_id INTEGER REFERENCES planet(id);