ALTER TABLE flight ADD COLUMN first_class_price REAL DEFAULT 0.0 NOT NULL;
ALTER TABLE flight ADD COLUMN business_price REAL DEFAULT 0.0 NOT NULL;
ALTER TABLE flight ADD COLUMN economy_price REAL DEFAULT 0.0 NOT NULL;